name: Deploy database to the development stand
on: workflow_dispatch
permissions: {}
env:
  CONTAINER_NAME: ${{ github.event.repository.name }}
jobs:
  deploy_database:
    name: Deploy database
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Run container
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
            docker network create database_net || true
            docker volume create database_vol || true
            docker run -d \
              --name ${{ env.CONTAINER_NAME }} \
              --restart unless-stopped \
              --network database_net \
              -e TZ=Europe/Moscow \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
              -v database_vol:/var/lib/postgresql/data \
              --health-cmd="pg_isready -U postgres" \
              --health-interval=10s \
              --health-timeout=5s \
              --health-retries=5 \
              --start-period=5s \
              ${{ vars.IMAGE }}
